# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'httparty', '~> 0.18.1'
gem 'nokogiri', '~> 1.11'
gem 'rspec', '~> 3.10'
