# See https://gitlab.com/gitlab-com/support/toolbox/espanso

name: gitlab-support
parent: default

global_vars:
  - name: "clipboard"
    type: "clipboard"

matches:

  # Relevant helper tools

  - trigger: '/sartpom'
    replace: 'shortly after reproducing the problem once more.'

  - trigger: '/itarf'
    replace: 'in the affected repository folder (which needs to be a full, up-to-date clone)'

  - trigger: "[gsos"
    replace: "[run our `GitLabSOS` script](https://gitlab.com/gitlab-com/support/toolbox/gitlabsos#run-the-script) {{sartpom}}"
    vars:
      - name: sartpom
        type: match
        params:
          trigger: '/sartpom'

  - trigger: "[ksos"
    replace: "[run our `KubeSOS` script](https://gitlab.com/gitlab-com/support/toolbox/kubesos#kubesos) {{sartpom}}"
    vars:
      - name: sartpom
        type: match
        params:
          trigger: '/sartpom'

  - trigger: '[gfs'
    replace: '[run `fast-stats $|$`](https://gitlab.com/gitlab-com/support/toolbox/fast-stats/#when-to-use-it) (binaries available [here](https://gitlab.com/gitlab-com/support/toolbox/fast-stats/-/releases))'

  - trigger: '[gsz'
    replace: '[run `git-sizer`](https://github.com/github/git-sizer#getting-started) {{itarf}}'

  - trigger: '[gfr'
    replace: '[run `git filter-repo --analyze`](https://github.com/newren/git-filter-repo/#how-do-i-install-it) {{itarf}}'

  # Add Support- & Review Guideline-related quick actions
  # See https://about.gitlab.com/handbook/engineering/ux/technical-writing/#designated-technical-writers,
  # https://docs.gitlab.com/ee/development/code_review.html#dogfooding-the-reviewers-feature,
  # and https://about.gitlab.com/handbook/support/engineering/#support-team-contributions
  - trigger: "/stc"
    replace: "/label ~\"Support Team Contributions\"\n/assign me\n/assign_reviewer \n/milestone %15."
  - trigger: '/ber'
    replace: "bundle exec rspec {{clipboard}}\n"
    vars:
      - name: "clipboard"
        type: "clipboard"


  # Components of verbose Markdown links, see below
  - trigger: '/glt'
    replace: "{{title}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: title
        type: shell
        params:
          cmd: 'ruby "$(espanso path packages)"/gitlab-support/title.rb ${ESPANSO_CLIPBOARD}'
  - trigger: '/glref'
    replace: "{{refer}}"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: refer
        type: shell
        params:
          cmd: 'ruby "$(espanso path packages)"/gitlab-support/reference.rb ${ESPANSO_CLIPBOARD}'

  # Format verbose issue/MR/epics links in Markdown (nested triggers from above)
  - trigger: '[tr)'
    replace: "[{{title}} ({{refer}})]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: title
        type: match
        params:
          trigger: '/glt'
      - name: refer
        type: match
        params:
          trigger: '/glref'
  - trigger: '[rt)'
    replace: "[{{refer}} ({{title}})]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: title
        type: match
        params:
          trigger: '/glt'
      - name: refer
        type: match
        params:
          trigger: '/glref'
  - trigger: '[r)'
    replace: "[{{refer}}]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: refer
        type: match
        params:
          trigger: '/glref'


  # Customer comments for issues after internal requests
  #   1. copy internal URL into clipboard
  #   2. summarize / partial-quote if necessary/useful
  - trigger: "~cfb"
    replace: "- Link to request: {{clipboard}} (internal)\nPriority: ~customer priority::$|$ \nWhy interested: \nCurrent solution for this problem: \nImpact to the customer of not having this: \nQuestions: \nPM to mention: @"

  - trigger: '[sst'
    replace: "See [Slack thread]({{clipboard}})\n\n> $|$"
    vars:
      - name: "clipboard"
        type: "clipboard"

  # filenames & paths
  - trigger: '.gcy'
    replace: '.gitlab-ci.yml'
  - trigger: '/eg'
    replace: '/etc/gitlab/'
  - trigger: '.grb'
    replace: 'gitlab.rb'
  - trigger: '.gsj'
    replace: 'gitlab-secrets.json'

  - trigger: '`gcy'
    replace: "`{{gcy}}`"
    vars:
      - name: gcy
        type: match
        params:
          trigger: '.gcy'
  - trigger: '`grb'
    replace: "`{{grb}}`"
    vars:
      - name: grb
        type: match
        params:
          trigger: '.grb'
  - trigger: '`gsj'
    replace: "`{{gsj}}`"
    vars:
      - name: gsj
        type: match
        params:
          trigger: '.gsj'

  # Omnibus paths
  #   https://docs.gitlab.com/ee/administration/logs.html
  #   https://docs.gitlab.com/ee/raketasks/backup_restore.html
  - trigger: '/vlg'
    replace: '/var/log/gitlab/'
  - trigger: '/og'
    replace: '/opt/gitlab/'
  - trigger: '/ebg'
    replace: "sudo -u git {{og}}embedded/bin/git"
    vars:
      - name: og
        type: match
        params:
          trigger: '/og'
  - trigger: '/vog'
    replace: "/var{{og}}"
    vars:
      - name: og
        type: match
        params:
          trigger: '/og'
  - trigger: '/vob'
    replace: "{{vog}}backups"
    vars:
      - name: vog
        type: match
        params:
          trigger: '/vog'
  - trigger: '/vodr'
    replace: "{{vog}}git-data/repositories/{{clipboard}}"
    vars:
      - name: vog
        type: match
        params:
          trigger: '/vog'

  # https://docs.gitlab.com/omnibus/maintenance/index.html
  - trigger: '/gctl'
    replace: 'sudo gitlab-ctl tail | tee /tmp/gl-{{clipboard}}-$|$.txt'
  - trigger: '/glcf'
    replace: 'sudo gitlab-ctl reconfigure'
  - trigger: '/glst'
    replace: 'sudo gitlab-ctl status'
  - trigger: '/glrt'
    replace: 'sudo gitlab-ctl restart'
  - trigger: '/glsp'
    replace: 'sudo gitlab-ctl stop'

  # Shell commands for use in SSH sessions on support-resources
  - trigger: '&sde'
    replace: 'shutdown && exit'
  - trigger: '/glsri'
    replace: |
      # Support-Resource initialization with a minimal configuration,
      # pinned version & some useful configs
      GRB=/etc/gitlab/gitlab.rb

      # Block Gravatar
      sudo echo '127.0.0.1 gravatar.com' >> /etc/hosts

      # Clear config file & insert a few useful items
      sudo sed \
          -e 's/#.*$//;/^$/d' \
          --in-place=.ori \
          $GRB && \
      echo "gitlab_rails['usage_ping_enabled'] = false" >> $GRB && \
      echo "logging['logrotate_frequency'] = nil" >> $GRB && \
      echo "logging['logrotate_size'] = '5G'" >> $GRB && \
      sudo gitlab-ctl reconfigure &&

      # Install tools and upgrades without changing GitLab
      sudo apt-mark hold {*g,g}itlab* &&
      apt install --yes ripgrep jq &&
      sudo apt --yes upgrade &&
      sudo reboot


  # Miscellaneous

  - trigger: "*(Q"
    replace: "**(Q$|$)** "

  - trigger: "(urg"
    replace: "([using `ripgrep` there](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md))"

  - trigger: "[jq"
    replace: "[jq](https://docs.gitlab.com/ee/administration/troubleshooting/log_parsing.html)"

  - trigger: "[sd"
    replace: "[sd](https://github.com/chmln/sd#sd---search--displace)"

  - trigger: "[Rc"
    replace: "[Rails console](https://docs.gitlab.com/ee/administration/operations/rails_console.html)"

  - trigger: "<ds"
    replace: "<details><summary>$|$</summary>{{clipboard}}</details>"

  - trigger: "c-a-b:"
    replace: "Co-authored-by: $|$ <@gitlab.com>"
    # Alternative: https://github.com/tj/git-extras/blob/master/Commands.md#git-coauthor

  - trigger: '[ZD'
    replace: '[ZD {{id}}]({{clipboard}})'
    vars:
      - name: id
        type: shell
        params:
          cmd: 'echo ${ESPANSO_CLIPBOARD} | grep -oE "\d+$"'

  # Slack messages

  - trigger: ':glspair'
    replace: ':pair: :support-tanuki: $|${{refer}}'
    vars:
      - name: refer
        type: match
        params:
          trigger: '/glref'

  - trigger: ':tfcc'
    replace: ':thread: for customer call about :zendesk: . cc @'

  - trigger: ':tfe'
    replace: ':thread: for emergency :point_up:'
