# See https://gitlab.com/gitlab-com/support/toolbox/espanso

name: gitlab-support
parent: default

global_vars:
  - name: "clipboard"
    type: "clipboard"

matches:

  # GitLabSOS & KubeSOS
  - trigger: "[gsos"
    replace: "[our `GitLabSOS` tool](https://gitlab.com/gitlab-com/support/toolbox/gitlabsos#run-the-script) shortly after reproducing the problem once more."
  - trigger: "[ksos"
    replace: "[our `KubeSOS` tool](https://gitlab.com/gitlab-com/support/toolbox/kubesos#kubesos) shortly after reproducing the problem once more."

  # Add Support- & Review Guideline-related quick actions
  # See https://about.gitlab.com/handbook/engineering/ux/technical-writing/#designated-technical-writers,
  # https://docs.gitlab.com/ee/development/code_review.html#dogfooding-the-reviewers-feature,
  # and https://about.gitlab.com/handbook/support/engineering/#support-team-contributions
  - trigger: "/stc"
    replace: "/label ~\"Support Team Contributions\"\n/assign me\n/assign_reviewer @"


  # Components of verbose Markdown links, see below

  - trigger: '""title'
    replace: "\"{{title}}\""
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: title
        type: shell
        params:
          cmd: 'ruby "$(espanso path packages)"/gitlab-support/title.rb ${ESPANSO_CLIPBOARD}'
  - trigger: '()refer'
    replace: "({{refer}})"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: refer
        type: shell
        params:
          cmd: 'ruby "$(espanso path packages)"/gitlab-support/reference.rb ${ESPANSO_CLIPBOARD}'

  # Format verbose issue/MR/epics links in Markdown (nested triggers from above)
  - trigger: '["('
    replace: "[$|$ {{title}} {{refer}}]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"
      - name: title
        type: match
        params:
          trigger: '""title'
      - name: refer
        type: match
        params:
          trigger: '()refer'


  # Customer comments for issues after internal requests
  #   1. copy internal URL into clipboard
  #   2. add (partial) quote if available
  - trigger: "~cc"
    replace: "A ~customer [internally]({{clipboard}}) is $|$:\n\n> "
  - trigger: "~pcc"
    replace: "A ~\"GitLab Premium\" ~customer [internally]({{clipboard}}) is $|$:\n\n> "
  - trigger: "~ucc"
    replace: "A ~\"GitLab Ultimate\" ~customer [internally]({{clipboard}}) is $|$:\n\n> "
  - trigger: "~lpcc"
    replace: "A large ~\"GitLab Premium\" ~customer [internally]({{clipboard}}) is $|$:\n\n> "
  - trigger: "~lucc"
    replace: "A large ~\"GitLab Ultimate\" ~customer [internally]({{clipboard}}) is $|$:\n\n> "

  - trigger: '[sst'
    replace: "See [Slack thread]({{clipboard}})\n\n> $|$"
    vars:
      - name: "clipboard"
        type: "clipboard"
